addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 5a3cf647-f98d-47f4-abe6-4817783c1501
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 720 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install:
- mvn clean
- git clone -b travis `git config --get remote.origin.url` target/travis
- cp target/travis/settings.xml ~/.m2/settings.xml
- cp target/travis/logging.properties logging.properties
branches: ''
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: IvdIao/ZBKZ7KcMdbnbpPH5dyujVnr1PAlE9hV+Nu5YujloIDUqTFpSFXB+wnp0CLMlW2kBR6YBhh71mp5M2XSqf+PtWB3b+ts7oz1vwhfUI857P5lMBHapekkNJk874sMjPdAUIprRnRBmVBfZVLMrSDE7LKqnuHXZjSkDGFYk=
  - secure: XCtBrBNHGL+c55erAzMGgfCbS7dXSAFrMqIQCiPD6ib9rde3G8aDMvsseY7jSO2ygspB4ubVr+WqNkC5yHMcNUQvkX/auNpSkJbzBFG/2lhC9NBvBAiFJZn5jmcVnQ19vgO2Zjd37B1NrIwT7sW49eVeG0zn/A+qRxWeagPy3SQ=
  - secure: YBbdzseg5yDFpQIiMoc3P2BTmqef4o+KAvrLMEbobXjIkiglUQ7UHCoRWClX74fTKAwuC7JvK7o5xJGLnaY43jJADXrGtE8/d44HNJaieE67mNosDYtOiA0iI2uIRFCAnXJCZ8f/iHx2xVMHMNWlwyoil4IUcjj+D7FRcsT5alE=
  - secure: Od7BwllgFXVfzFe8ooTNm05TR+Xd5QjHW0oqhU8vclaQs2oX4e0eNIsebXQfLi3xDgd1pz5uUQC/Z4S0NqACwyUuUvPdGYYmRPTR7Dh8HgGJ4ojSdN3RwaHsxUqG7Ajts9rIHOtRpY28xOChVRNX0Z7eAPlvxYU4Ed2ZEo356r0=
  - secure: ROxa8HHuba+Dfixljq6poW1+Uwv8EaZUtTTTB7KEtAHJRN8rwoNS4TC0U0PEHcYAL+ivxP3zIfWOCoWreJGoa+V8y9BtLSuamUj/SSsuoHRdJjq5BmcHI/77P11HAzCH6Ul/GxsRB52/IRHwJyfKkh8XUMVSsCl7AG4CKUgt63Y=
  - secure: MKZ3y6IYp3Z67T+BO4Brw+my8sRMSMdWWgvUcyBpwQZ64w7ccHJCce4W8WHCPNko/eczHHCJELPG28VNyPTWIV/Jt2ZJ6L9qLCjsQpDPOdJdDaAKc9Df4sm8fB0FBiPVDwMYPQF1/Sy2gK7FZf0YR3LOeoyzswRgmj5bQMdVEeU=
install: mvn install --quiet -Djava.util.logging.config.file=logging.properties -DskipTests=true
  -Dgpg.skip=true
language: java
matrix:
  include:
  - before_install:
    - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
      $HOME/.m2/settings.xml
    env: JAVA_HOME=$(/usr/libexec/java_home)
    os: osx
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=5a3cf647-f98d-47f4-abe6-4817783c1501
script:
- travis_wait 60 utilities/verify.sh
# Modified by Insights Service at 2016-11-27 17:43:58.475118
